pub mod algorithms;
pub mod basis;
pub mod errors;
pub mod generators;
pub mod grids;
pub mod hierarchisation;
pub mod iterators;
mod lagrange;
pub mod multi_index_manipulation;
pub mod refinement;
pub mod rules;
pub mod storage;
mod tables;