pub mod algorithms;
pub mod base_generator;
pub mod errors;
pub mod grids;
pub mod generators;
pub mod iterators;
pub mod multi_index_manipulation;
pub mod one_dimensional_nodes;
pub mod rules;
pub mod tensor;
mod lagrange;
mod bounded_sum_iterator;
pub mod storage;
pub mod hierarchisation;
pub mod basis;
pub mod refinement;
pub(crate) mod tables;